# **Atelier Préparation de Données Images**

## **Partie 1 – Exploration du dataset**

### **1.1 Développer un programme Python capable de récupérer, pour chaque image, son nom, sa classe, son format, son mode, sa largeur, sa hauteur, l’écart-type de ses pixels, son nombre de canaux et sa taille.**

In [15]:
import os
import numpy as np
import pandas as pd
from PIL import Image

RAW_DIR = "../data/raw"

In [ ]:
def get_image_info(filepath, classe):
    """Récupère les infos d'une image. Gère aussi le cas d'un fichier corrompu."""
    nom = os.path.basename(filepath)
    taille_octets = os.path.getsize(filepath)

    try:
        with Image.open(filepath) as img:
            img.load()  # force la lecture complète des pixels (détecte les fichiers corrompus)
            pixels = np.array(img)
            corrompu = False
            
    except Exception:
        corrompu = True

    return {
        "nom": nom,
        "classe": classe,
        "format": None,
        "mode": None,
        "largeur": None,
        "hauteur": None,
        "ecart_type_pixels": None,
        "nb_canaux": None,
        "taille_octets": taille_octets,
        "corrompue": corrompu,
    }

In [17]:
lignes = []

for classe in sorted(os.listdir(RAW_DIR)):
    dossier_classe = os.path.join(RAW_DIR, classe)
    for nom_fichier in sorted(os.listdir(dossier_classe)):
        chemin_image = os.path.join(dossier_classe, nom_fichier)
        lignes.append(get_image_info(chemin_image, classe))

df_images = pd.DataFrame(lignes)

print(f"Nombre total d'images : {len(df_images)}")
df_images.head()

Nombre total d'images : 1032

,nom,classe,format,mode,largeur,hauteur,ecart_type_pixels,nb_canaux,taille_octets,corrompue
0,cardboard1.jpg,cardboard,JPEG,RGB,512.0,384.0,40.588529,3.0,17333,False
1,cardboard10.jpg,cardboard,JPEG,RGB,512.0,384.0,42.571288,3.0,21683,False
2,cardboard100.jpg,cardboard,JPEG,RGB,512.0,384.0,46.108305,3.0,14884,False
3,cardboard101.jpg,cardboard,JPEG,RGB,512.0,384.0,72.263996,3.0,14289,False
4,cardboard102.jpg,cardboard,JPEG,RGB,512.0,384.0,48.388937,3.0,18015,False

In [18]:
df_images[df_images['corrompue'] == True]

,nom,classe,format,mode,largeur,hauteur,ecart_type_pixels,nb_canaux,taille_octets,corrompue
147,cardboard83.jpg,cardboard,NaN,NaN,NaN,NaN,NaN,NaN,20888,True
326,glass74.jpg,glass,NaN,NaN,NaN,NaN,NaN,NaN,7184,True
446,metal48.jpg,metal,NaN,NaN,NaN,NaN,NaN,NaN,7259,True
633,paper213.jpg,paper,NaN,NaN,NaN,NaN,NaN,NaN,7293,True
791,plastic13.jpg,plastic,NaN,NaN,NaN,NaN,NaN,NaN,5250,True
1004,trash3.jpg,trash,NaN,NaN,NaN,NaN,NaN,NaN,9192,True

## **Partie 2 – Détecter les images corrompues**

### **2.1 Ecriture d'une fonction qui détecte une image corrompue.**

In [ ]:
def image_corrompu(file_path, classe):
     nom = os.path.basename(file_path)
     taille_octets = os.path.getsize(file_path)
     try:
          with Image.open(file_path) as img:
               img.load() # exection levée si l'image est corrompu
               corrompu = False
     except Exception:
          corrompu = True

     return{
               "nom": nom,
               "taille": taille_octets,
               "classe": classe,
               "corrompu": True
          }

In [22]:
images_corrompu = []

for classe in sorted(os.listdir(RAW_DIR)):
    dossier_classe = os.path.join(RAW_DIR, classe)
    for nom_fichier in sorted(os.listdir(dossier_classe)):
        chemin_image = os.path.join(dossier_classe, nom_fichier)
        images_corrompu.append(image_corrompu(chemin_image, classe))

df_images_corrompu = pd.DataFrame(images_corrompu)
df_corrompues = df_images_corrompu[df_images_corrompu["corrompu"] == True]

print(f"Nombre total d'images : {len(df_images_corrompu)}")
print(f"Nombre d'images corrompues : {len(df_corrompues)}")
df_corrompues

Nombre total d'images : 1032
Nombre d'images corrompues : 6

                  nom  taille     classe  corrompu
147   cardboard83.jpg   20888  cardboard      True
326       glass74.jpg    7184      glass      True
446       metal48.jpg    7259      metal      True
633      paper213.jpg    7293      paper      True
791     plastic13.jpg    5250    plastic      True
1004       trash3.jpg    9192      trash      True